== API HTTP

The Z-Wave plugin implements a complete API so developers and users can operate the Z-Wave network via HTTP requests.

Il vous est possible d'exploiter l'ensemble des méthodes exposées par le serveur REST du démon Z-Wave.

The syntax to invoke routes is as follows :

URL = http://token:\#APIKEY#@\#IP_JEEDOM#:\#PORTDEMON#/\#ROUTE#

* \#API_KEY# correspond à votre clé API, propre à votre installation. Pour la trouver, il faut aller dans le menu « Général », puis « Administration » et « Configuration », en activant le mode Expert, vous verrez alors une ligne Clef API.

* \#IP_JEEDOM# corresponds to access url to Jeedom.

* \#PORTDEMON# corresponds to the port ID specified on the Z-Wave plugin configuration screen ; 8083 by default.

* \#ROUTE# corresponds to the route to be invoked on the REST server.

Pour connaitre l'ensemble des routes, veuillez vous référer
link:https://github.com/jeedom/plugin-openzwave[github] of the Z-Wave plugin.

Example :
To Ping node with ID 2

URL = \http://token:a1b2c3d4e5f6g7h8@192.168.0.1:8083/ZWaveAPI/Run/devices[[2]].TestNode()