== API HTTP

The Z-Wave plugin implements a complete API so developers and users can operate the Z-Wave network via HTTP requests.

It is possible to invoke the whole set of methods that are exposed by the REST server of the Z-Wave daemon.

The syntax to invoke routes is as follows :

URL = http://token:\#APIKEY#@\#IP_JEEDOM#:\#PORTDEMON#/\#ROUTE#

* \#API_KEY# corresponds to your API key, custom to your installation. To find it, go to the "General" menu, then "Administration" and "Configuration", and having activated the expert mode, you will see the API key information.

* \#IP_JEEDOM# corresponds to access url to Jeedom.

* \#PORTDEMON# corresponds to the port ID specified on the Z-Wave plugin configuration screen ; 8083 by default.

* \#ROUTE# corresponds to the route to be invoked on the REST server.

To have the list of all possible routes, please refer to
link:https://github.com/jeedom/plugin-openzwave[github] of the Z-Wave plugin.

Example :
To Ping node with ID 2

URL = \http://token:a1b2c3d4e5f6g7h8@192.168.0.1:8083/ZWaveAPI/Run/devices[[2]].TestNode()