== API HTTP

Le plugin Z-Wave met à disposition des développeurs et des utilisateurs une API complète afin de pouvoir opérer le réseau Z-Wave via requête HTTP.

Il vous est possible d'exploiter, l'ensemble des méthodes exposé par le serveur REST du démon Z-Wave.

La syntaxe pour appeler les routes est sous cette forme:

URL = http://token:\#APIKEY#@\#IP_JEEDOM#:\#PORTDEMON#/\#ROUTE#

* \#API_KEY# correspond à votre clé API, propre à votre installation. Pour la trouver il faut aller dans le menu « Général », puis « Administration » et « Configuration », en activant le mode Expert vous verrez alors une ligne Clef API.

* \#IP_JEEDOM# correspond à votre url d’accès à Jeedom.

* \#PORTDEMON# correspond au numéro de port spécifié dans la page de configuration du plugin Z-Wave, par défaut: 8083.

* \#ROUTE# correspond à la route sur le serveur REST a exécuter.

Pour connaitre l'ensemble des route veillez vous référer
link:https://github.com/jeedom/plugin-openzwave[github] du plugin Z-Wave.

Example:
Pour lancer un ping sur le noeud id 2

URL = \http://token:a1b2c3d4e5f6g7h8@192.168.0.1:8083/ZWaveAPI/Run/devices[[2]].TestNode()
