J'ai le message d'erreur suivant "ImportError: No module named flask" ou "ImportError: No module named openzwave"::
Un ou plusieurs module requit n'est pas trouvé. Veuillez relancer la mise à jour des dépendances.

''''

Je ne vois pas ma clé dans le menu::
Voir ici : https://wiki.jeedom.fr/index.php?title=OpenZwave#D.C3.A9bogage

''''

Quand je vais sur la santé j'ai des erreurs 404 ?::
Vérifier la configuration réseau jeedom. forcer la sauvegarde des paramètres réseau, puis relancer le plugin Z-Wave.

''''

Je ne vois pas le bouton "Stable" en face de "Installer/Mettre à jour OpenZwave en local"::
Votre Jeedom n'a pas les droits sudo un message d'erreur doit vous indiquer la marche à suivre

''''

Je n'arrive pas installer les dependances openzwave::
Essayer de le lancer manuellement en SSH : 
----
sudo su -
chmod +x /usr/share/nginx/www/jeedom/plugins/openzwave/ressources/install.sh
/usr/share/nginx/www/jeedom/plugins/openzwave/ressources/install.sh
----

''''
Je modifie les parametres de mon module et la ligne reste en jaune avec l'ancienne valeur
Les modules sur pile vont appliquer les changement de paramètres seulement au prochain cycle de réveille. Il est toute fois possible de le réveiller à la main un module, voir la documentation du module.

''''
Je modifie les parametres de mon module et la ligne passe en rouge
Le module n'a pas accepté la valeur. Dans certain cas il faut essayer a plusieurs reprise. Il est aussi possible que la valeur ne soit vraiment pas compatible avec le module. 



