J'ai le message d'erreur suivant "ImportError: No module named flask"::
Il y a eu un problème lors de l'exécution de la commande d'installation. Merci de relancer celle-ci.

''''

Je ne vois pas ma clé dans le menu::
Voir ici : https://wiki.jeedom.fr/index.php?title=OpenZwave#D.C3.A9bogage

''''

Quand je vais sur la configuration j'ai des erreurs 404 ?::
Il faut verifier si l'étape visudo de la doc d'installation à bien été faite (valable uniquement en DIY pas sur les images) https://www.jeedom.fr/doc/documentation/installation/fr_FR/doc-installation.html#_etape_4_définition_des_droits_root_à_jeedom:ici

''''

Quand je vais sur la santé j'ai des erreurs 404 ?::
Cela arrive sur certaine configuration il faut essayer de désactiver le "direct push" (voir tout au début, la configuration du plugin) et relancer le démon

''''

Je ne vois pas le bouton "Stable" en face de "Installer/Mettre à jour OpenZwave en local"::
Votre Jeedom n'a pas les droits sudo un message d'erreur doit vous indiquer la marche à suivre

''''

Je n'arrive pas installer les dependances openzwave::
Essayer de le lancer manuellement en SSH : 
----
sudo su -
chmod +x /usr/share/nginx/www/jeedom/plugins/openzwave/ressources/install.sh
/usr/share/nginx/www/jeedom/plugins/openzwave/ressources/install.sh
----